#!/usr/bin/env python3
"""Generate the MuJoCo model (MJCF) of the 9-DoF parallel robot.

Reads config/geometry.yaml and config/dynamics.yaml and writes
mujoco/ninedof.xml (robot) and mujoco/scene.xml (robot + floor + light).

Unlike URDF, MJCF can close the kinematic loops: each distal link hangs from
its actuator with a ball joint and its upper ball A_i is tied to the platform
with an equality "connect" constraint. The model is written in its home
configuration so that qpos0 is an assembled robot.

    python3 scripts/generate_mjcf.py            # from the package directory
"""

import math
import os

import numpy as np
import yaml

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Finger plates of each platform (platform frame, metres), measured on the
# meshes: base quad (z = 5 mm), bend (z ~ 18-19 mm) and tip (z ~ 36-40 mm).
FINGER = {
    1: {'base': [[-17.82, 6.09, 5.0], [-9.67, 7.61, 5.0], [-11.9, 3.14, 5.0], [-15.59, 10.57, 5.0]],
        'bend': [[-17.21, 5.79, 17.73], [-14.98, 10.26, 17.73],
                 [-23.67, 9.01, 19.0], [-21.44, 13.48, 19.0]],
        'tip': [[1.35, 2.12, 35.97], [-0.89, -2.35, 35.97],
                [-2.45, 4.02, 40.21], [-4.68, -0.46, 40.21]]},
    2: {'base': [[11.9, -3.14, 5.0], [15.59, -10.57, 5.0], [9.67, -7.61, 5.0], [17.82, -6.09, 5.0]],
        'bend': [[17.21, -5.79, 17.73], [14.98, -10.26, 17.73],
                 [23.67, -9.01, 19.0], [21.44, -13.48, 19.0]],
        'tip': [[-1.35, -2.12, 35.97], [0.89, 2.35, 35.97],
                [2.45, -4.02, 40.21], [4.68, 0.46, 40.21]]},
}


def fmt(v):
    return ' '.join(f'{x:.6g}' for x in np.atleast_1d(v))


def quat_z_to(u):
    """Quaternion (w x y z) rotating +Z onto the unit vector u."""
    z = np.array([0.0, 0.0, 1.0])
    axis = np.cross(z, u)
    s = np.linalg.norm(axis)
    if s < 1e-12:
        return np.array([1.0, 0.0, 0.0, 0.0])
    angle = math.atan2(s, float(z @ u))
    axis /= s
    return np.r_[math.cos(angle / 2), axis * math.sin(angle / 2)]


def disk_inertia(mass, radius, height):
    ixx = mass * (3 * radius ** 2 + height ** 2) / 12
    return [ixx, ixx, mass * radius ** 2 / 2]


def rod_inertia(mass, length):
    """Slender rod along Z, centre of mass at its middle."""
    ixx = mass * length ** 2 / 12
    return [ixx, ixx, 1e-9]


def generate(geometry, dynamics):
    g = geometry['ninedof']
    d = dynamics['ninedof_dynamics']
    l = g['distal_length']
    ball_h = g['slider_ball_height']
    stroke = g['actuator_stroke']
    home = np.array([0.0, 0.0, g['home_z']])
    act = d['actuator']
    m = d['mass']

    out = []
    w = out.append
    w('<!-- Generated by scripts/generate_mjcf.py from config/geometry.yaml and')
    w('     config/dynamics.yaml. Do not edit by hand. -->')
    w('<mujoco model="ninedof">')
    w('  <compiler angle="radian" meshdir="../meshes" autolimits="true"/>')
    # Stiff loop closures (ideal joints) need a small time step.
    w('  <option timestep="0.0005" integrator="implicitfast"/>')
    w('')
    w('  <default>')
    w('    <default class="visual">')
    w('      <geom type="mesh" contype="0" conaffinity="0" group="2" mass="0"/>')
    w('    </default>')
    w('    <default class="finger">')
    w(f'      <geom type="mesh" contype="2" conaffinity="1" group="3" mass="0" '
      f'friction="{d["finger_friction"]} 0.005 0.0001" rgba="0.9 0.6 0.1 0.4"/>')
    w('    </default>')
    w('    <equality solref="0.001 1" solimp="0.99 0.999 0.0001"/>')
    w('  </default>')
    w('')
    w('  <asset>')
    for name in ('base', 'slider', 'distal_link', 'platform_1', 'platform_2'):
        w(f'    <mesh name="{name}" file="{name}.stl"/>')
    for k, f in FINGER.items():
        lower = np.array(f['base'] + f['bend']) / 1000.0
        upper = np.array(f['bend'] + f['tip']) / 1000.0
        w(f'    <mesh name="finger_{k}_lower" vertex="{fmt(lower.ravel())}"/>')
        w(f'    <mesh name="finger_{k}_upper" vertex="{fmt(upper.ravel())}"/>')
    w('    <material name="base_grey" rgba="0.75 0.75 0.75 1"/>')
    w('    <material name="rod_white" rgba="0.92 0.92 0.92 1"/>')
    w('    <material name="platform_1_red" rgba="0.80 0.25 0.20 1"/>')
    w('    <material name="platform_2_blue" rgba="0.20 0.40 0.80 1"/>')
    w('  </asset>')
    w('')
    w('  <worldbody>')
    w(f'    <body name="base_link">')
    w(f'      <geom class="visual" mesh="base" material="base_grey" '
      f'pos="0 0 {g["base_mesh_offset_z"]}"/>')

    # Legs: slider on a slide joint, distal link on a ball joint at B_i.
    legs = g['legs']
    a_world = []
    for leg in legs:
        a = np.array(leg['a'])
        a_world.append(home + a)
    for leg, A in zip(legs, a_world):
        n = leg['name']
        B = np.array([leg['base_x'], leg['base_y'], leg['base_z0']])
        u = (A - B) / np.linalg.norm(A - B)
        w(f'      <body name="{n}_slider" pos="{fmt([B[0], B[1], B[2] - ball_h])}">')
        w(f'        <joint name="{n}_actuator_joint" type="slide" axis="0 0 1" '
          f'range="{-stroke} {stroke}" armature="{act["armature"]}" '
          f'actuatorfrcrange="{-act["max_force"]} {act["max_force"]}"/>')
        w(f'        <inertial pos="0 0 {ball_h / 2:.6g}" mass="{m["slider"]}" '
          f'diaginertia="{fmt(rod_inertia(m["slider"], ball_h))}"/>')
        w(f'        <geom class="visual" mesh="slider" material="rod_white"/>')
        w(f'        <body name="{n}_distal" pos="0 0 {ball_h}" quat="{fmt(quat_z_to(u))}">')
        w(f'          <joint name="{n}_lower_joint" type="ball" '
          f'damping="{d["passive_joint_damping"]}"/>')
        w(f'          <inertial pos="0 0 {l / 2}" mass="{m["distal_link"]}" '
          f'diaginertia="{fmt(rod_inertia(m["distal_link"], l))}"/>')
        w(f'          <geom class="visual" mesh="distal_link" material="rod_white"/>')
        w(f'          <site name="{n}_A" pos="0 0 {l}" size="0.002"/>')
        w('        </body>')
        w('      </body>')
    w('    </body>')
    w('')

    # Platforms: platform 1 floats (its pose is imposed by legs 1-5), platform 2
    # hangs from it through the central spherical joint.
    w(f'    <body name="platform_1" pos="{fmt(home)}">')
    w('      <freejoint name="platform_1_free"/>')
    w(f'      <inertial pos="0 0 0.005" mass="{m["platform_1"]}" '
      f'diaginertia="{fmt(disk_inertia(m["platform_1"], 0.035, 0.01))}"/>')
    w('      <geom class="visual" mesh="platform_1" material="platform_1_red"/>')
    w('      <geom class="finger" mesh="finger_1_lower"/>')
    w('      <geom class="finger" mesh="finger_1_upper"/>')
    w('      <body name="platform_2">')
    w(f'        <joint name="central_sphere_joint" type="ball" '
      f'damping="{d["passive_joint_damping"]}"/>')
    w(f'        <inertial pos="0 0 0.005" mass="{m["platform_2"]}" '
      f'diaginertia="{fmt(disk_inertia(m["platform_2"], 0.035, 0.01))}"/>')
    w('        <geom class="visual" mesh="platform_2" material="platform_2_blue"/>')
    w('        <geom class="finger" mesh="finger_2_lower"/>')
    w('        <geom class="finger" mesh="finger_2_upper"/>')
    w('      </body>')
    w('    </body>')
    w('  </worldbody>')
    w('')

    # Close the loops: upper ball A_i of each distal link on its platform.
    w('  <equality>')
    for leg in legs:
        n = leg['name']
        w(f'    <connect name="{n}_upper_joint" body1="{n}_distal" '
          f'body2="platform_{leg["platform"]}" anchor="0 0 {l}"/>')
    w('  </equality>')
    w('')
    w('  <contact>')
    w('    <exclude body1="platform_1" body2="platform_2"/>')
    w('  </contact>')
    w('')
    # Position servos named like the ros2_control joints (mujoco_ros2_control).
    w('  <actuator>')
    for leg in legs:
        n = leg['name']
        w(f'    <position name="{n}_actuator_joint" joint="{n}_actuator_joint" '
          f'kp="{act["kp"]}" dampratio="{act["damping_ratio"]}" '
          f'ctrlrange="{-stroke} {stroke}" forcerange="{-act["max_force"]} {act["max_force"]}"/>')
    w('  </actuator>')
    w('')
    w('  <sensor>')
    for leg in legs:
        n = leg['name']
        w(f'    <actuatorfrc name="{n}_force" actuator="{n}_actuator_joint"/>')
    w('  </sensor>')
    w('</mujoco>')
    return '\n'.join(out) + '\n'


SCENE = """<!-- MuJoCo scene of the 9-DoF parallel robot. -->
<mujoco model="ninedof_scene">
  <include file="ninedof.xml"/>

  <statistic center="0 0 0.08" extent="0.3"/>
  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.3 0.3 0.3" specular="0 0 0"/>
    <global azimuth="135" elevation="-20"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4"
             rgb2="0.1 0.2 0.3" markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5"
              reflectance="0.2"/>
  </asset>

  <worldbody>
    <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
    <geom name="floor" pos="0 0 -0.03" size="0 0 0.05" type="plane" material="groundplane"
          contype="1" conaffinity="1"/>
  </worldbody>
</mujoco>
"""


def main():
    with open(os.path.join(PKG, 'config', 'geometry.yaml')) as f:
        geometry = yaml.safe_load(f)
    with open(os.path.join(PKG, 'config', 'dynamics.yaml')) as f:
        dynamics = yaml.safe_load(f)
    os.makedirs(os.path.join(PKG, 'mujoco'), exist_ok=True)
    with open(os.path.join(PKG, 'mujoco', 'ninedof.xml'), 'w') as f:
        f.write(generate(geometry, dynamics))
    with open(os.path.join(PKG, 'mujoco', 'scene.xml'), 'w') as f:
        f.write(SCENE)
    print('Wrote mujoco/ninedof.xml and mujoco/scene.xml')


if __name__ == '__main__':
    main()
